project_id = "cfkdasmhlqswpunugbkf"

[functions.buyer-transactions]
verify_jwt = false

[functions.buyer-disputes]
verify_jwt = false

[functions.buyer-profile]
verify_jwt = false

[functions.upload-evidence]
verify_jwt = false

[functions.transaction-detail]
verify_jwt = false

[functions.decline-transaction]
verify_jwt = false