project_id = "cfkdasmhlqswpunugbkf"

[functions.buyer-transactions]
verify_jwt = false

[functions.buyer-disputes]
verify_jwt = false

[functions.buyer-profile]
verify_jwt = false

[functions.upload-evidence]
verify_jwt = false

[functions.transaction-detail]
verify_jwt = false

[functions.decline-transaction]
verify_jwt = false

[functions.initiate-paystack-payment]
verify_jwt = false

[functions.verify-paystack-payment]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.seller-dashboard]
verify_jwt = false

[functions.seller-transactions]
verify_jwt = false

[functions.create-transaction]
verify_jwt = false

[functions.seller-drafts]
verify_jwt = false

[functions.seller-transaction-detail]
verify_jwt = false

[functions.update-delivery-status]
verify_jwt = false

[functions.seller-payouts]
verify_jwt = false

[functions.update-payout-account]
verify_jwt = false

[functions.seller-profile]
verify_jwt = false

[functions.seller-disputes]
verify_jwt = false
