import { scanKeyboardRepo, scanFontRepo } from "./src/__tests__/helpers/touch-target-scan";
const k = scanKeyboardRepo("src").filter(v=>!v.file.includes("__tests__"));
const f = scanFontRepo("src").filter(v=>!v.file.includes("__tests__"));
for (const x of k) console.log("KB", `${x.file}:${x.line}`, x.reason);
console.log("KB TOTAL", k.length);
const byFile = new Map<string, number>();
for (const x of f) byFile.set(x.file, (byFile.get(x.file) ?? 0) + 1);
console.log("FONT TOTAL", f.length, "files", byFile.size);
const sizes = new Set(f.map(x=>/text-\[(\d+(?:\.\d+)?)px\]/.exec(x.snippet)?.[1]));
console.log("sizes", [...sizes].join(","));
