import { useState } from "react";
import {
  Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

export const REPORT_TYPES = [
  { value: "workload", label: "Workload report" },
  { value: "performance", label: "Performance report" },
  { value: "sla", label: "SLA compliance report" },
  { value: "rankings", label: "Rankings report" },
  { value: "filtered_agent", label: "Filtered agent report" },
] as const;

export function ExportPerformanceDialog({
  open, onOpenChange, tabLabel, rowCount, onConfirm, busy, defaultReport, agents, rangeLabel,
}: {
  open: boolean;
  onOpenChange: (v: boolean) => void;
  tabLabel: string;
  rowCount: number;
  onConfirm: (opts: { maskPii: boolean; reason: string; report: string; agentId: string | null }) => void;
  busy: boolean;
  /** Report pre-selected from the active tab. */
  defaultReport: string;
  agents: { user_id: string; name: string }[];
  rangeLabel: string;
}) {
  const [maskPii, setMaskPii] = useState(true);
  const [reason, setReason] = useState("");
  const [report, setReport] = useState(defaultReport);
  const [agentId, setAgentId] = useState<string>("");
  const effectiveReport = open ? report : defaultReport;
  const needsAgent = effectiveReport === "filtered_agent";
  const valid = reason.trim().length >= 20 && (!needsAgent || !!agentId);

  return (
    <Dialog
      open={open}
      onOpenChange={(v) => { if (v) { setReport(defaultReport); setAgentId(""); } onOpenChange(v); }}
    >
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Export performance report</DialogTitle>
          <DialogDescription>
            Exporting from the <strong>{tabLabel}</strong> view · {rangeLabel} · {rowCount}{" "}
            {rowCount === 1 ? "agent" : "agents"} with the current filters applied. The file records the
            date range, applied filters, generated date and generated by. This export is audit logged.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4">
          <div className="space-y-1.5">
            <Label className="text-sm">Report type</Label>
            <Select value={report} onValueChange={setReport}>
              <SelectTrigger className="h-11" aria-label="Report type"><SelectValue /></SelectTrigger>
              <SelectContent>
                {REPORT_TYPES.map((r) => <SelectItem key={r.value} value={r.value}>{r.label}</SelectItem>)}
              </SelectContent>
            </Select>
          </div>

          {needsAgent && (
            <div className="space-y-1.5">
              <Label className="text-sm">Agent</Label>
              <Select value={agentId} onValueChange={setAgentId}>
                <SelectTrigger className="h-11" aria-label="Agent to export">
                  <SelectValue placeholder="Select an agent" />
                </SelectTrigger>
                <SelectContent>
                  {agents.map((a) => <SelectItem key={a.user_id} value={a.user_id}>{a.name}</SelectItem>)}
                </SelectContent>
              </Select>
            </div>
          )}

          <div className="flex items-center justify-between rounded-xl border border-border/60 bg-card/60 p-3">
            <div>
              <Label htmlFor="mask-pii" className="text-sm">Mask personal data</Label>
              <p className="text-xs text-muted-foreground">Hides agent emails in the CSV.</p>
            </div>
            <Switch id="mask-pii" checked={maskPii} onCheckedChange={setMaskPii} />
          </div>

          <div className="space-y-1.5">
            <Label htmlFor="export-reason" className="text-sm">Reason (min 20 characters)</Label>
            <Textarea
              id="export-reason"
              value={reason}
              onChange={(e) => setReason(e.target.value)}
              rows={3}
              placeholder="Why is this export needed?"
            />
            <p className="text-[11px] text-muted-foreground">{reason.trim().length}/20</p>
          </div>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)} disabled={busy}>Cancel</Button>
          <Button
            onClick={() => onConfirm({
              maskPii, reason: reason.trim(), report,
              agentId: needsAgent ? agentId : null,
            })}
            disabled={!valid || busy}
          >
            {busy ? "Exporting…" : "Export CSV"}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}